### PR TITLE
Create variables

### PR DESCRIPTION
**Pull request by jeremyjorand**

### CODE REVIEW

**Review by ThomasDCW — APPROVED** [review]
ok for me

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by ThomasDCW — APPROVED** [review]
Resolve conflict

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
