### PR TITLE
Fixnavbaronclick

### PR DESCRIPTION
**Pull request by ThomasDCW**
on this PR i refactored the navbar and fix routes nav links, on the nav bar now there is only one icon. the others icon will come when the others pages will be done.

### CODE REVIEW

**Review by ilalande — APPROVED** [review]

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Fix conflict

**Review by Dash293 — APPROVED** [review]

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
