### PR TITLE
create img audio

### PR DESCRIPTION
**Pull request by jeremyjorand**

### CODE REVIEW

**Review by ThomasDCW — DISMISSED** [review]
looks ok

**Review by LuigiMenez — DISMISSED** [review]
Ok for me

**Review by LoicBrassart — APPROVED** [review]
SnE

**Review by ThomasDCW — DISMISSED** [review]
fixed

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
