### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by jeremyjorand**

### CODE REVIEW

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by ThomasDCW — DISMISSED** [review]
ok

**Review by ThomasDCW — APPROVED** [review]
ok

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
