### PR TITLE
Removing AudioPlayerControll component put in AudioPlayerLoading in o…

### PR DESCRIPTION
**Pull request by ilalande**
…rder to connect the range input wirh play button

### CODE REVIEW

**Review by ThomasDCW — DISMISSED** [review]

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by ThomasDCW — APPROVED** [review]

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
