### PR TITLE
Add delete favorite2.0

### PR DESCRIPTION
**Pull request by ilalande**
Correcting old code to make it work

### CODE REVIEW

**Review by ThomasDCW — DISMISSED** [review]
Ok

**Review by ThomasDCW — APPROVED** [review]
ok for me

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Fix minor

**Comment by ilalande** [comment]
Hi luigi, as it i's written in the Comment juste ahead, for the moment and wainting for authentification we donc it on user 2. It's mean't to be changed as soin as wé have authentification. It's to stay simple and not spend time on useless technical issues - how to delete with to variables. And be able to not be blocked wainting fir authentification

**Comment by ilalande** [comment]
Sorry for bad spelling ( my smartphone corrects English...)

**Comment by LoicBrassart** [comment]
Like Luigi said: Don't use hard-coded values.
We won't let you introduce faulty code on the `dev` branch at this stage of the project.
If you need full auth for this feature, it should get to `dev` **before**. Then you'll fix this code and reopen this PR, and we'll review it

**Pull request closed without merging**
