### PR TITLE
003 stream css 1.0

### PR DESCRIPTION
**Pull request by ilalande**

### CODE REVIEW

**Review by ThomasDCW — APPROVED** [review]
looks ok

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — CHANGES_REQUESTED** [review]
Please fix those, it'll save your time later

**Review by ThomasDCW — APPROVED** [review]
ok

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
